<?php
// pre-reserved names

// we can probably add lots more....
// See also
// * http://blog.postbit.com/reserved-username-list.html
// * https://gist.github.com/caseyohara/1453705
// * https://www.google.com/search?q=suggested+reserved+names
// * https://github.com/shutterstock/List-of-Dirty-Naughty-Obscene-and-Otherwise-Bad-Words

return array(

    // misc names / Generic reserved words
    'about'           => 1,
    'aboutu'          => 1,
    'access'          => 1,
    'account'         => 1,
    'activate'        => 1,
    'activity'        => 1,
    'add'             => 1,
    'address'         => 1,
    'adm'             => 1,
    'admanager'       => 1,
    'admin'           => 1,
    'admindashboard'  => 1,
    'administrador'   => 1,
    'administration'  => 1,
    'administrator'   => 1,
    'admins'          => 1,
    'adminweb'        => 1,
    'admissions'      => 1,
    'ads'             => 1,
    'advertising'     => 1,
    'affiliate'       => 1,
    'afp'             => 1,
    'agent'           => 1,
    'ajax'            => 1,
    'alias'           => 1,
    'all'             => 1,
    'alpha'           => 1,
    'analysis'        => 1,
    'analytic'        => 1,
    'analytics'       => 1,
    'android'         => 1,
    'anon'            => 1,
    'anonymous'       => 1,
    'answer'          => 1,
    'api'             => 1,
    'app'             => 1,
    'application'     => 1,
    'appnew'          => 1,
    'archive'         => 1,
    'article'         => 1,
    'asct'            => 1,
    'asdf'            => 1,
    'asset'           => 1,
    'atom'            => 1,
    'audio'           => 1,
    'auth'            => 1,
    'authentication'  => 1,
    'avatar'          => 1,
    'backup'          => 1,
    'balancer'        => 1,
    'balancermanager' => 1,
    'bank'            => 1,
    'banner'          => 1,
    'base'            => 1,
    'beginner'        => 1,
    'beta'            => 1,
    'better'          => 1,
    'billing'         => 1,
    'bin'             => 1,
    'binarie'         => 1,
    'binary'          => 1,
    'biz'             => 1,
    'blog'            => 1,
    'blogsearch'      => 1,
    'board'           => 1,
    'book'            => 1,
    'bookmark'        => 1,
    'boss'            => 1,
    'bot'             => 1,
    'bug'             => 1,
    'business'        => 1,
    'buy'             => 1,
    'buzz'            => 1,
    'c'               => 1,
    'cache'           => 1,
    'cadastro'        => 1,
    'calendar'        => 1,
    'call'            => 1,
    'campaign'        => 1,
    'cancel'          => 1,
    'captcha'         => 1,
    'career'          => 1,
    'careers'         => 1,
    'cart'            => 1,
    'case'            => 1,
    'catalog'         => 1,
    'categories'      => 1,
    'category'        => 1,
    'cdrom'           => 1,
    'cgi'             => 1,
    'cgibin'          => 1,
    'changelog'       => 1,
    'chart'           => 1,
    'chat'            => 1,
    'checkout'        => 1,
    'client'          => 1,
    'cliente'         => 1,
    'cname'           => 1,
    'cnarne'          => 1,
    'code'            => 1,
    'codereview'      => 1,
    'comercial'       => 1,
    'comment'         => 1,
    'comments'        => 1,
    'commercial'      => 1,
    'communities'     => 1,
    'community'       => 1,
    'company'         => 1,
    'compare'         => 1,
    'compras'         => 1,
    'computer'        => 1,
    'config'          => 1,
    'configuration'   => 1,
    'confirm'         => 1,
    'confirmation'    => 1,
    'connect'         => 1,
    'contact'         => 1,
    'contact-u'       => 1,
    'contactu'        => 1,
    'contactus'       => 1,
    'content'         => 1,
    'contest'         => 1,
    'contribute'      => 1,
    'contributors'    => 1,
    'controlpanel'    => 1,
    'core'            => 1,
    'corp'            => 1,
    'count'           => 1,
    'countrie'        => 1,
    'country'         => 1,
    'cp'              => 1,
    'create'          => 1,
    'css'             => 1,
    'dashboard'       => 1,
    'data'            => 1,
    'db'              => 1,
    'dbadmin'         => 1,
    'default'         => 1,
    'delete'          => 1,
    'demo'            => 1,
    'demouser'        => 1,
    'denied'          => 1,
    'deploy'          => 1,
    'deployment'      => 1,
    'design'          => 1,
    'designer'        => 1,
    'desktop'         => 1,
    'destroy'         => 1,
    'dev'             => 1,
    'devdata'         => 1,
    'devel'           => 1,
    'develop'         => 1,
    'developement'    => 1,
    'developer'       => 1,
    'development'     => 1,
    'device'          => 1,
    'diagram'         => 1,
    'diary'           => 1,
    'dic'             => 1,
    'dict'            => 1,
    'dictionaries'    => 1,
    'dictionary'      => 1,
    'die'             => 1,
    'dir'             => 1,
    'directmessage'   => 1,
    'directory'       => 1,
    'discussion'      => 1,
    'dist'            => 1,
    'dl'              => 1,
    'doc'             => 1,
    'document'        => 1,
    'documentation'   => 1,
    'domain'          => 1,
    'donate'          => 1,
    'download'        => 1,
    'e'               => 1,
    'earth'           => 1,
    'ecommerce'       => 1,
    'edit'            => 1,
    'editor'          => 1,
    'edu'             => 1,
    'education'       => 1,
    'else'            => 1,
    'email'           => 1,
    'empty'           => 1,
    'enable'          => 1,
    'encrypted'       => 1,
    'end'             => 1,
    'engine'          => 1,
    'enterprise'      => 1,
    'entry'           => 1,
    'error'           => 1,
    'errorlog'        => 1,
    'eval'            => 1,
    'event'           => 1,
    'example'         => 1,
    'exit'            => 1,
    'explore'         => 1,
    'faq'             => 1,
    'favorite'        => 1,
    'feature'         => 1,
    'feed'            => 1,
    'feedback'        => 1,
    'feedproxy'       => 1,
    'file'            => 1,
    'finance'         => 1,
    'find'            => 1,
    'firefly'         => 1,
    'first'           => 1,
    'flash'           => 1,
    'fleet'           => 1,
    'flog'            => 1,
    'folder'          => 1,
    'follow'          => 1,
    'follower'        => 1,
    'following'       => 1,
    'for'             => 1,
    'forgot'          => 1,
    'forgotpassword'  => 1,
    'form'            => 1,
    'forum'           => 1,
    'founder'         => 1,
    'free'            => 1,
    'friend'          => 1,
    'fun'             => 1,
    'fusion'          => 1,
    'gadget'          => 1,
    'game'            => 1,
    'gear'            => 1,
    'geographic'      => 1,
    'get'             => 1,
    'gettingstarted'  => 1,
    'gift'            => 1,
    'gist'            => 1,
    'global'          => 1,
    'goto'            => 1,
    'graph'           => 1,
    'group'           => 1,
    'guest'           => 1,
    'hack'            => 1,
    'hacker'          => 1,
    'hello'           => 1,
    'help'            => 1,
    'helpdesk'        => 1,
    'home'            => 1,
    'homepage'        => 1,
    'host'            => 1,
    'hosting'         => 1,
    'hostname'        => 1,
    'howto'           => 1,
    'hpg'             => 1,
    'html'            => 1,
    'htrnl'           => 1,
    'http'            => 1,
    'httpd'           => 1,
    'https'           => 1,
    'i'               => 1,
    'icon'            => 1,
    'idea'            => 1,
    'if'              => 1,
    'image'           => 1,
    'imap'            => 1,
    'img'             => 1,
    'index'           => 1,
    'indice'          => 1,
    'infomation'      => 1,
    'information'     => 1,
    'inquiry'         => 1,
    'intranet'        => 1,
    'investor'        => 1,
    'invitation'      => 1,
    'invite'          => 1,
    'invoice'         => 1,
    'ipad'            => 1,
    'iphone'          => 1,
    'irc'             => 1,
    'irnage'          => 1,
    'irng'            => 1,
    'issue'           => 1,
    'item'            => 1,
    'j'               => 1,
    'java'            => 1,
    'javascript'      => 1,
    'job'             => 1,
    'join'            => 1,
    'js'              => 1,
    'json'            => 1,
    'jump'            => 1,
    'knowledgebase'   => 1,
    'lab'             => 1,
    'lang'            => 1,
    'language'        => 1,
    'last'            => 1,
    'ldapstatus'      => 1,
    'legal'           => 1,
    'license'         => 1,
    'link'            => 1,
    'list'            => 1,
    'local'           => 1,
    'locale'          => 1,
    'location'        => 1,
    'log'             => 1,
    'login'           => 1,
    'logout'          => 1,
    'm'               => 1,
    'mac'             => 1,
    'magic'           => 1,
    'mail'            => 1,
    'mailbox'         => 1,
    'mailing'         => 1,
    'mailnull'        => 1,
    'mailtest'        => 1,
    'maintenance'     => 1,
    'manage'          => 1,
    'manager'         => 1,
    'manual'          => 1,
    'map'             => 1,
    'master'          => 1,
    'matrix'          => 1,
    'media'           => 1,
    'member'          => 1,
    'message'         => 1,
    'messenger'       => 1,
    'microblog'       => 1,
    'mine'            => 1,
    'mis'             => 1,
    'misc'            => 1,
    'mms'             => 1,
    'mob'             => 1,
    'mobile'          => 1,
    'model'           => 1,
    'mom'             => 1,
    'monday'          => 1,
    'money'           => 1,
    'movie'           => 1,
    'mp3'             => 1,
    'msg'             => 1,
    'msn'             => 1,
    'music'           => 1,
    'musicas'         => 1,
    'mystore'         => 1,
    'n'               => 1,
    'name'            => 1,
    'nan'             => 1,
    'navi'            => 1,
    'navigation'      => 1,
    'net'             => 1,
    'network'         => 1,
    'new'             => 1,
    'newsite'         => 1,
    'newsletter'      => 1,
    'nick'            => 1,
    'nickname'        => 1,
    'nobody'          => 1,
    'nologin'         => 1,
    'note'            => 1,
    'noticias'        => 1,
    'notify'          => 1,
    'ns'              => 1,
    'null'            => 1,
    'oauth'           => 1,
    'oauthclient'     => 1,
    'off'             => 1,
    'offer'           => 1,
    'office'          => 1,
    'official'        => 1,
    'old'             => 1,
    'on'              => 1,
    'online'          => 1,
    'openid'          => 1,
    'operator'        => 1,
    'or'              => 1,
    'order'           => 1,
    'org'             => 1,
    'organization'    => 1,
    'other'           => 1,
    'out'             => 1,
    'overview'        => 1,
    'owner'           => 1,
    'owners'          => 1,
    'pack'            => 1,
    'page'            => 1,
    'pager'           => 1,
    'panel'           => 1,
    'partner'         => 1,
    'partnerpage'     => 1,
    'password'        => 1,
    'payment'         => 1,
    'people'          => 1,
    'perl'            => 1,
    'person'          => 1,
    'phone'           => 1,
    'photo'           => 1,
    'photoalbum'      => 1,
    'php'             => 1,
    'pic'             => 1,
    'place'           => 1,
    'plan'            => 1,
    'plugin'          => 1,
    'podcast'         => 1,
    'policy'          => 1,
    'pop'             => 1,
    'pop3'            => 1,
    'popular'         => 1,
    'portal'          => 1,
    'post'            => 1,
    'premium'         => 1,
    'press'           => 1,
    'price'           => 1,
    'pricing'         => 1,
    'print'           => 1,
    'privacy'         => 1,
    'privacypolicy'   => 1,
    'private'         => 1,
    'prod'            => 1,
    'product'         => 1,
    'production'      => 1,
    'profile'         => 1,
    'project'         => 1,
    'promo'           => 1,
    'promotion'       => 1,
    'proxie'          => 1,
    'proxies'         => 1,
    'proxy'           => 1,
    'pub'             => 1,
    'public'          => 1,
    'purchase'        => 1,
    'purpose'         => 1,
    'put'             => 1,
    'python'          => 1,
    'qiita'           => 1,
    'querie'          => 1,
    'queries'         => 1,
    'query'           => 1,
    'r'               => 1,
    'radio'           => 1,
    'random'          => 1,
    'ranking'         => 1,
    'read'            => 1,
    'reader'          => 1,
    'reboot'          => 1,
    'recent'          => 1,
    'recently'        => 1,
    'recover'         => 1,
    'recruit'         => 1,
    'redirect'        => 1,
    'register'        => 1,
    'registration'    => 1,
    'release'         => 1,
    'remove'          => 1,
    'replies'         => 1,
    'report'          => 1,
    'repositories'    => 1,
    'repository'      => 1,
    'req'             => 1,
    'request'         => 1,
    'reserved'        => 1,
    'reset'           => 1,
    'resolve'         => 1,
    'resolver'        => 1,
    'rnail'           => 1,
    'roc'             => 1,
    'root'            => 1,
    'rootalias'       => 1,
    'router'          => 1,
    'rpc'             => 1,
    'rss'             => 1,
    'ruby'            => 1,
    'rule'            => 1,
    'sag'             => 1,
    'sale'            => 1,
    'sample'          => 1,
    'sandbox'         => 1,
    'save'            => 1,
    'scholar'         => 1,
    'school'          => 1,
    'script'          => 1,
    'search'          => 1,
    'secure'          => 1,
    'securityagent'   => 1,
    'select'          => 1,
    'self'            => 1,
    'seminar'         => 1,
    'send'            => 1,
    'server'          => 1,
    'serverinfo'      => 1,
    'serverstatus'    => 1,
    'service'         => 1,
    'session'         => 1,
    'setting'         => 1,
    'setup'           => 1,
    'share'           => 1,
    'shop'            => 1,
    'shopping'        => 1,
    'shortcut'        => 1,
    'show'            => 1,
    'shutdown'        => 1,
    'signin'          => 1,
    'signout'         => 1,
    'signup'          => 1,
    'site'            => 1,
    'sitemap'         => 1,
    'sitenew'         => 1,
    'sky'             => 1,
    'slash'           => 1,
    'slashinvoice'    => 1,
    'smartphone'      => 1,
    'sms'             => 1,
    'smtp'            => 1,
    'software'        => 1,
    'soporte'         => 1,
    'sorry'           => 1,
    'source'          => 1,
    'spam'            => 1,
    'spamd'           => 1,
    'spec'            => 1,
    'special'         => 1,
    'spreadsheet'     => 1,
    'sql'             => 1,
    'src'             => 1,
    'srntp'           => 1,
    'ssh'             => 1,
    'ssl'             => 1,
    'ssladmin'        => 1,
    'ssladministrator'=> 1,
    'sslwebmaster'    => 1,
    'staff'           => 1,
    'stage'           => 1,
    'staging'         => 1,
    'star'            => 1,
    'start'           => 1,
    'stat'            => 1,
    'state'           => 1,
    'static'          => 1,
    'statistic'       => 1,
    'statu'           => 1,
    'status'          => 1,
    'stmp'            => 1,
    'store'           => 1,
    'stories'         => 1,
    'style'           => 1,
    'styleguide'      => 1,
    'stylesheet'      => 1,
    'subdomain'       => 1,
    'subscribe'       => 1,
    'subscription'    => 1,
    'suggest'         => 1,
    'suggestquerie'   => 1,
    'suggestquery'    => 1,
    'supermansysadmin'=> 1,
    'suporte'         => 1,
    'supportdetail'   => 1,
    'survey'          => 1,
    'surveytool'      => 1,
    'svg'             => 1,
    'swf'             => 1,
    'switch'          => 1,
    'sync'            => 1,
    'sys'             => 1,
    'sysadmin'        => 1,
    'sysadministrator'=> 1,
    'sysop'           => 1,
    'system'          => 1,
    'tablet'          => 1,
    'tag'             => 1,
    'talk'            => 1,
    'talkgadget'      => 1,
    'task'            => 1,
    'team'            => 1,
    'tech'            => 1,
    'telnet'          => 1,
    'telnettheme'     => 1,
    'tempuser'        => 1,
    'term'            => 1,
    'termservice'     => 1,
    'termsofservice'  => 1,
    'termsservice'    => 1,
    'test'            => 1,
    'teste'           => 1,
    'tester'          => 1,
    'testing'         => 1,
    'text'            => 1,
    'theme'           => 1,
    'then'            => 1,
    'thread'          => 1,
    'tmp'             => 1,
    'todo'            => 1,
    'tool'            => 1,
    'toolbar'         => 1,
    'toor'            => 1,
    'top'             => 1,
    'topic'           => 1,
    'tour'            => 1,
    'transfer'        => 1,
    'translate'       => 1,
    'translation'     => 1,
    'translator'      => 1,
    'trend'           => 1,
    'trending'        => 1,
    'trends'          => 1,
    'tutorial'        => 1,
    'tux'             => 1,
    'tweetdeck'       => 1,
    'txt'             => 1,
    'ul'              => 1,
    'undef'           => 1,
    'unfollow'        => 1,
    'unsubscribe'     => 1,
    'update'          => 1,
    'upload'          => 1,
    'url'             => 1,
    'usage'           => 1,
    'user'            => 1,
    'username'        => 1,
    'usuario'         => 1,
    'validate'        => 1,
    'validation'      => 1,
    'vendas'          => 1,
    'ver'             => 1,
    'version'         => 1,
    'vid'             => 1,
    'video'           => 1,
    'video-stat'      => 1,
    'virus'           => 1,
    'visitor'         => 1,
    'voice'           => 1,
    'vvvvvv'          => 1,    // a bit like www
    'w'               => 1,
    'watch'           => 1,
    'wave'            => 1,
    'weather'         => 1,
    'web'             => 1,
    'webdisk'         => 1,
    'webmin'          => 1,
    'webrnail'        => 1,
    'website'         => 1,
    'webuser'         => 1,
    'welcome'         => 1,
    'when'            => 1,
    'whm'             => 1,
    'whoi'            => 1,
    'widget'          => 1,
    'wifi'            => 1,
    'wiki'            => 1,
    'win'             => 1,
    'word'            => 1,
    'work'            => 1,
    'workshop'        => 1,
    'ww'              => 1,
    'wws'             => 1,
    'wwww'            => 1,
    'xfn'             => 1,
    'xhtml'           => 1,
    'xhtrnl'          => 1,
    'xml'             => 1,
    'xmpp'            => 1,
    'xpg'             => 1,
    'yaml'            => 1,
    'year'            => 1,
    'yml'             => 1,
    'you'             => 1,
    'yourdomain'      => 1,
    'yourname'        => 1,
    'yoursite'        => 1,
    'yourusername'    => 1,

    // Top 50 languages by speaking population
    'arabic'          => 1,
    'awadhi'          => 1,
    'azerbaijani'     => 1,
    'bengali'         => 1,
    'bhojpuri'        => 1,
    'burmese'         => 1,
    'chinese'         => 1,
    'dutch'           => 1,
    'english'         => 1,
    'farsi'           => 1,
    'french'          => 1,
    'gan'             => 1,
    'german'          => 1,
    'gujarati'        => 1,
    'hakka'           => 1,
    'hausa'           => 1,
    'hindi'           => 1,
    'italian'         => 1,
    'japanese'        => 1,
    'javanese'        => 1,
    'jinyu'           => 1,
    'kannada'         => 1,
    'korean'          => 1,
    'maithili'        => 1,
    'malayalam'       => 1,
    'mandarin'        => 1,
    'marathi'         => 1,
    'minnan'          => 1,
    'oriya'           => 1,
    'panjabi'         => 1,
    'polish'          => 1,
    'portuguese'      => 1,
    'romanian'        => 1,
    'russian'         => 1,
    'serbocroatian'   => 1,
    'sindhi'          => 1,
    'spanish'         => 1,
    'sunda'           => 1,
    'tamil'           => 1,
    'telugu'          => 1,
    'thai'            => 1,
    'turkish'         => 1,
    'ukrainian'       => 1,
    'urdu'            => 1,
    'vietnamese'      => 1,
    'wu'              => 1,
    'xiang'           => 1,
    'yoruba'          => 1,

    // rude/explicit
    'adult'           => 1,
    'anal'            => 1,
    'anus'            => 1,
    'arse'            => 1,
    'ass'             => 1,
    'balls'           => 1,
    'ballsack'        => 1,
    'bastard'         => 1,
    'biatch'          => 1,
    'bitch'           => 1,
    'bloody'          => 1,
    'blowjob'         => 1,
    'bollock'         => 1,
    'bollok'          => 1,
    'boner'           => 1,
    'boob'            => 1,
    'bugger'          => 1,
    'bum'             => 1,
    'butt'            => 1,
    'buttplug'        => 1,
    'clitoris'        => 1,
    'cock'            => 1,
    'coon'            => 1,
    'crap'            => 1,
    'cunt'            => 1,
    'damn'            => 1,
    'dick'            => 1,
    'dildo'           => 1,
    'dyke'            => 1,
    'fag'             => 1,
    'feck'            => 1,
    'felching'        => 1,
    'fellate'         => 1,
    'fellatio'        => 1,
    'flange'          => 1,
    'frack'           => 1,
    'frak'            => 1,
    'fuck'            => 1,
    'fudgepacker'     => 1,
    'gay'             => 1,
    'gaylord'         => 1,
    'goddamn'         => 1,
    'hell'            => 1,
    'homo'            => 1,
    'jerk'            => 1,
    'jizz'            => 1,
    'knobend'         => 1,
    'labia'           => 1,
    'lmao'            => 1,
    'lmfao'           => 1,
    'muff'            => 1,
    'nigga'           => 1,
    'nigger'          => 1,
    'omg'             => 1,
    'p0rn'            => 1,
    'penis'           => 1,
    'piss'            => 1,
    'poop'            => 1,
    'porn'            => 1,
    'pr0n'            => 1,
    'prick'           => 1,
    'pube'            => 1,
    'pussy'           => 1,
    'queer'           => 1,
    'scrotum'         => 1,
    'sex'             => 1,
    'sh1t'            => 1,
    'shit'            => 1,
    'slut'            => 1,
    'smegma'          => 1,
    'spunk'           => 1,
    'suck'            => 1,
    'thissitesucks'   => 1,
    'thissucks'       => 1,
    'tit'             => 1,
    'tosser'          => 1,
    'turd'            => 1,
    'twat'            => 1,
    'vagina'          => 1,
    'wank'            => 1,
    'whore'           => 1,
    'wtf'             => 1,
    'xxx'             => 1,

    // Country TLDs
    'ac'              => 1,  # Ascension Island
    'ad'              => 1,  # Andorra
    'ae'              => 1,  # United Arab Emirates
    'af'              => 1,  # Afghanistan
    'ag'              => 1,  # Antigua and Barbuda
    'ai'              => 1,  # Anguilla
    'al'              => 1,  # Albania
    'am'              => 1,  # Armenia
    'an'              => 1,  # Netherlands Antilles
    'ao'              => 1,  # Angola
    'aq'              => 1,  # Antarctica
    'ar'              => 1,  # Argentina
    'as'              => 1,  # American Samoa
    'at'              => 1,  # Austria
    'au'              => 1,  # Australia
    'aw'              => 1,  # Aruba
    'ax'              => 1,  # and
    'az'              => 1,  # Azerbaijan
    'ba'              => 1,  # Bosnia and Herzegovina
    'bb'              => 1,  # Barbados
    'bd'              => 1,  # Bangladesh
    'be'              => 1,  # Belgium
    'bf'              => 1,  # Burkina Faso
    'bg'              => 1,  # Bulgaria
    'bh'              => 1,  # Bahrain
    'bi'              => 1,  # Burundi
    'bj'              => 1,  # Benin
    'bm'              => 1,  # Bermuda
    'bn'              => 1,  # Brunei Darussalam
    'bo'              => 1,  # Bolivia
    'br'              => 1,  # Brazil
    'bs'              => 1,  # Bahamas
    'bt'              => 1,  # Bhutan
    'bv'              => 1,  # Bouvet Island
    'bw'              => 1,  # Botswana
    'by'              => 1,  # Belarus
    'bz'              => 1,  # Belize
    'ca'              => 1,  # Canada
    'cc'              => 1,  # Cocos (Keeling) Islands
    'cd'              => 1,  # Democratic Republic of the Congo
    'cf'              => 1,  # Central African Republic
    'cg'              => 1,  # Republic of the Congo
    'ch'              => 1,  # Switzerland
    'ci'              => 1,  # CÃ´te d'Ivoire
    'ck'              => 1,  # Cook Islands
    'cl'              => 1,  # Chile
    'cm'              => 1,  # Cameroon
    'cn'              => 1,  # People's Republic of China
    'co'              => 1,  # Colombia
    'cr'              => 1,  # Costa Rica
    'cs'              => 1,  # Czechoslovakia
    'cu'              => 1,  # Cuba
    'cv'              => 1,  # Cape Verde
    'cx'              => 1,  # Christmas Island
    'cy'              => 1,  # Cyprus
    'cz'              => 1,  # Czech Republic
    'dd'              => 1,  # East Germany
    'de'              => 1,  # Germany
    'dj'              => 1,  # Djibouti
    'dk'              => 1,  # Denmark
    'dm'              => 1,  # Dominica
    'do'              => 1,  # Dominican Republic
    'dz'              => 1,  # Algeria
    'ec'              => 1,  # Ecuador
    'ee'              => 1,  # Estonia
    'eg'              => 1,  # Egypt
    'eh'              => 1,  # Western Sahara
    'er'              => 1,  # Eritrea
    'es'              => 1,  # Spain
    'et'              => 1,  # Ethiopia
    'eu'              => 1,  # European Union
    'fi'              => 1,  # Finland
    'fj'              => 1,  # Fiji
    'fk'              => 1,  # Falkland Islands
    'fm'              => 1,  # Federated States of Micronesia
    'fo'              => 1,  # Faroe Islands
    'fr'              => 1,  # France
    'ga'              => 1,  # Gabon
    'gb'              => 1,  # United Kingdom
    'gd'              => 1,  # Grenada
    'ge'              => 1,  # Georgia
    'gf'              => 1,  # French Guiana
    'gg'              => 1,  # Guernsey
    'gh'              => 1,  # Ghana
    'gi'              => 1,  # Gibraltar
    'gl'              => 1,  # Greenland
    'gm'              => 1,  # The Gambia
    'gn'              => 1,  # Guinea
    'gp'              => 1,  # Guadeloupe
    'gq'              => 1,  # Equatorial Guinea
    'gr'              => 1,  # Greece
    'gs'              => 1,  # South Georgia and the South Sandwich Islands
    'gt'              => 1,  # Guatemala
    'gu'              => 1,  # Guam
    'gw'              => 1,  # Guinea-Bissau
    'gy'              => 1,  # Guyana
    'hk'              => 1,  # Hong Kong
    'hm'              => 1,  # Heard Island and McDonald Islands
    'hn'              => 1,  # Honduras
    'hr'              => 1,  # Croatia
    'ht'              => 1,  # Haiti
    'hu'              => 1,  # Hungary
    'id'              => 1,  # Indonesia
    'ie'              => 1,  # Republic of Ireland  Northern Ireland
    'il'              => 1,  # Israel
    'im'              => 1,  # Isle of Man
    'in'              => 1,  # India
    'io'              => 1,  # British Indian Ocean Territory
    'iq'              => 1,  # Iraq
    'ir'              => 1,  # Iran
    'is'              => 1,  # Iceland
    'it'              => 1,  # Italy
    'je'              => 1,  # Jersey
    'jm'              => 1,  # Jamaica
    'jo'              => 1,  # Jordan
    'jp'              => 1,  # Japan
    'ke'              => 1,  # Kenya
    'kg'              => 1,  # Kyrgyzstan
    'kh'              => 1,  # Cambodia
    'ki'              => 1,  # Kiribati
    'km'              => 1,  # Comoros
    'kn'              => 1,  # Saint Kitts and Nevis
    'kp'              => 1,  # Democratic People's Republic of Korea
    'kr'              => 1,  # Republic of Korea
    'kw'              => 1,  # Kuwait
    'ky'              => 1,  # Cayman Islands
    'kz'              => 1,  # Kazakhstan
    'la'              => 1,  # Laos
    'lb'              => 1,  # Lebanon
    'lc'              => 1,  # Saint Lucia
    'li'              => 1,  # Liechtenstein
    'lk'              => 1,  # Sri Lanka
    'lr'              => 1,  # Liberia
    'ls'              => 1,  # Lesotho
    'lt'              => 1,  # Lithuania
    'lu'              => 1,  # Luxembourg
    'lv'              => 1,  # Latvia
    'ly'              => 1,  # Libya
    'ma'              => 1,  # Morocco
    'mc'              => 1,  # Monaco
    'md'              => 1,  # Moldova
    'me'              => 1,  # Montenegro
    'mg'              => 1,  # Madagascar
    'mh'              => 1,  # Marshall Islands
    'mk'              => 1,  # Republic of Macedonia
    'ml'              => 1,  # Mali
    'mm'              => 1,  # Myanmar
    'mn'              => 1,  # Mongolia
    'mo'              => 1,  # Macau
    'mp'              => 1,  # Northern Mariana Islands
    'mq'              => 1,  # Martinique
    'mr'              => 1,  # Mauritania
    'ms'              => 1,  # Montserrat
    'mt'              => 1,  # Malta
    'mu'              => 1,  # Mauritius
    'mv'              => 1,  # Maldives
    'mw'              => 1,  # Malawi
    'mx'              => 1,  # Mexico
    'my'              => 1,  # Malaysia
    'mz'              => 1,  # Mozambique
    'na'              => 1,  # Namibia
    'nc'              => 1,  # New Caledonia
    'ne'              => 1,  # Niger
    'nf'              => 1,  # Norfolk Island
    'ng'              => 1,  # Nigeria
    'ni'              => 1,  # Nicaragua
    'nl'              => 1,  # Netherlands
    'no'              => 1,  # Norway
    'np'              => 1,  # Nepal
    'nr'              => 1,  # Nauru
    'nu'              => 1,  # Niue
    'nz'              => 1,  # New Zealand
    'om'              => 1,  # Oman
    'pa'              => 1,  # Panama
    'pe'              => 1,  # Peru
    'pf'              => 1,  # French Polynesia
    'pg'              => 1,  # Papua New Guinea
    'ph'              => 1,  # Philippines
    'pk'              => 1,  # Pakistan
    'pl'              => 1,  # Poland
    'pm'              => 1,  # Saint-Pierre and Miquelon
    'pn'              => 1,  # Pitcairn Islands
    'pr'              => 1,  # Puerto Rico
    'ps'              => 1,  # Palestinian territories
    'pt'              => 1,  # Portugal
    'pw'              => 1,  # Palau
    'py'              => 1,  # Paraguay
    'qa'              => 1,  # Qatar
    're'              => 1,  # RÃ©union
    'ro'              => 1,  # Romania
    'rs'              => 1,  # Serbia
    'ru'              => 1,  # Russia
    'rw'              => 1,  # Rwanda
    'sa'              => 1,  # Saudi Arabia
    'sb'              => 1,  # Solomon Islands
    'sc'              => 1,  # Seychelles
    'sd'              => 1,  # Sudan
    'se'              => 1,  # Sweden
    'sg'              => 1,  # Singapore
    'sh'              => 1,  # Saint Helena
    'si'              => 1,  # Slovenia
    'sj'              => 1,  # Svalbard and  Jan Mayen Islands
    'sk'              => 1,  # Slovakia
    'sl'              => 1,  # Sierra Leone
    'sm'              => 1,  # San Marino
    'sn'              => 1,  # Senegal
    'so'              => 1,  # Somalia
    'sr'              => 1,  # Suriname
    'ss'              => 1,  # South Sudan
    'st'              => 1,  # SÃ£o TomÃ© and PrÃ­ncipe
    'su'              => 1,  # Soviet Union
    'sv'              => 1,  # El Salvador
    'sy'              => 1,  # Syria
    'sz'              => 1,  # Swaziland
    'tc'              => 1,  # Turks and Caicos Islands
    'td'              => 1,  # Chad
    'tf'              => 1,  # French Southern and Antarctic Lands
    'tg'              => 1,  # Togo
    'th'              => 1,  # Thailand
    'tj'              => 1,  # Tajikistan
    'tk'              => 1,  # Tokelau
    'tl'              => 1,  # East Timor
    'tm'              => 1,  # Turkmenistan
    'tn'              => 1,  # Tunisia
    'to'              => 1,  # Tonga
    'tp'              => 1,  # East Timor
    'tr'              => 1,  # Turkey
    'tt'              => 1,  # Trinidad and Tobago
    'tv'              => 1,  # Tuvalu
    'tw'              => 1,  # Republic of China (Taiwan)
    'tz'              => 1,  # Tanzania
    'ua'              => 1,  # Ukraine
    'ug'              => 1,  # Uganda
    'uk'              => 1,  # United Kingdom
    'us'              => 1,  # United States of America
    'uy'              => 1,  # Uruguay
    'uz'              => 1,  # Uzbekistan
    'va'              => 1,  # Vatican City
    'vc'              => 1,  # Saint Vincent and the Grenadines
    've'              => 1,  # Venezuela
    'vg'              => 1,  # British Virgin Islands
    'vi'              => 1,  # United States Virgin Islands
    'vn'              => 1,  # Vietnam
    'vu'              => 1,  # Vanuatu
    'wf'              => 1,  # Wallis and Futuna
    'ws'              => 1,  # Samoa
    'ye'              => 1,  # Yemen
    'yt'              => 1,  # Mayotte
    'yu'              => 1,  # Yugoslavia
    'za'              => 1,  # South Africa
    'zm'              => 1,  # Zambia
    'zw'              => 1,  # Zimbabwe

    // Companies/Orgs/SW we'd love to have use our service
    // so we'll reserve them to be safe
    'acme'            => 1,
    'adsense'         => 1,
    'adword'          => 1,
    'affiliatepage'   => 1,
    'ap'              => 1,
    'appengine'       => 1,
    'apple'           => 1,
    'blackberry'      => 1,
    'canonical'       => 1,
    'facebook'        => 1,
    'feedburner'      => 1,
    'github'          => 1,
    'gmail'           => 1,
    'google'          => 1,
    'gov'             => 1,
    'hailo'           => 1,
    'ibm'             => 1,
    'informix'        => 1,
    'ingres'          => 1,
    'ios'             => 1,
    'jira'            => 1,
    'nasa'            => 1,
    'oracle'          => 1,
    'redhat'          => 1,
    'rnicrosoft'      => 1,
    'sketchup'        => 1,
    'twitter'         => 1,
    'twittr'          => 1,
    'ubuntu'          => 1,
    'xbox'            => 1,
    'xerox'           => 1,
    'yahoo'           => 1,

    // misc software
    'apache'          => 1,
    'apache2'         => 1,
    'cacti'           => 1,
    'cpanel'          => 1,
    'cron'            => 1,
    'cvs'             => 1,
    'cvsroot'         => 1,
    'cvsuser'         => 1,
    'daemon'          => 1,
    'database'        => 1,
    'dhcp'            => 1,
    'dnscache'        => 1,
    'exim'            => 1,
    'fedora'          => 1,
    'firefox'         => 1,
    'firewall'        => 1,
    'ftpadmin'        => 1,
    'ftpd'            => 1,
    'ftpguest'        => 1,
    'ftptest'         => 1,
    'ftpuser'         => 1,
    'gateway'         => 1,
    'git'             => 1,
    'gitlab'          => 1,
    'go'              => 1,
    'hadoop'          => 1,
    'ingress'         => 1,
    'jenkin'          => 1,
    'linux'           => 1,
    'mailer'          => 1,
    'mailman'         => 1,
    'majordom'        => 1,
    'majordomo'       => 1,
    'mongrel'         => 1,
    'moodle'          => 1,
    'mysql'           => 1,
    'mythtv'          => 1,
    'nagios'          => 1,
    'named'           => 1,
    'npm'             => 1,
    'ntp'             => 1,
    'packagist'       => 1,
    'phpbb'           => 1,
    'postfix'         => 1,
    'postgres'        => 1,
    'postgresql'      => 1,
    'qmail'           => 1,
    'sftp'            => 1,
    'soap'            => 1,
    'svn'             => 1,
    'svnuser'         => 1,
    'trac'            => 1,
    'unix'            => 1,
    'webadmin'        => 1,
    'webalizer'       => 1,
    'webmail'         => 1,
    'wget'            => 1,
    'windows'         => 1,
    'wwwdata'         => 1,
    'zabbix'          => 1,
    'zenoss'          => 1,
    'zimbra'          => 1,

    // suggested as reserved by http://www.ietf.org/rfc/rfc2142.txt
    'abuse'           => 1,
    'ftp'             => 1,
    'hostmaster'      => 1,
    'info'            => 1,
    'marketing'       => 1,
    'news'            => 1,
    'noc'             => 1,
    'postmaster'      => 1,
    'sales'           => 1,
    'security'        => 1,
    'support'         => 1,
    'usenet'          => 1,
    'uucp'            => 1,
    'webmaster'       => 1,
    'www'             => 1,

    // people
    'billgates'       => 1,
    'ceo'             => 1,
    'fabpot'          => 1,
    'nutch'           => 1,
    'stevewozniak'    => 1,
    'woz'             => 1,
    'wozniak'         => 1,
);
