services:
    alister_reserved_names.cleanusername:
        # must implement Alister\ReservedNamesBundle\Services\CleanUserNamesInterface
        class: Alister\ReservedNamesBundle\Services\CleanUserNames
        public: true

    alister_reserved_names.check:
        # must implement Alister\ReservedNamesBundle\Services\ReservedNamesInterface
        class: Alister\ReservedNamesBundle\Services\ReservedNames
        public: true
        arguments:
            - "%alister_reserved_names.names%"
            - "@alister_reserved_names.cleanusername"
    Alister\ReservedNamesBundle\Services\ReservedNames: '@alister_reserved_names.check'
    Alister\ReservedNamesBundle\Services\CleanUserNames: '@alister_reserved_names.cleanusername'
