## Run on container environment
sudo: false

language: php

php:
- 7.2
- 7.3
- 7.4
- nightly

matrix:
  include:
    - php: '7.3'
      env: dependencies=lowest
    - php: '7.3'
      env: dependencies=highest
    - php: nightly
      env: dependencies=highest
  allow_failures:
    - php: nightly
    - php: 7.4
  fast_finish: true

## Cache composer bits, where possible
cache:
  directories:
    - vendor
    - $HOME/.composer/cache

before_script:
  - rm -rf /tmp/AlisterReservedNamesBundle
  - phpenv config-add .travis.php.ini
  - if [ -z "$dependencies" ]; then composer install; fi;
  - if [ "$dependencies" = "lowest" ]; then rm -rf vendor; composer update --prefer-lowest --no-interaction ; fi;
  - if [ "$dependencies" = "highest" ]; then composer update --no-interaction ; fi;
  - composer install --prefer-dist
  - sudo apt-get -y install ant
  - "curl -H 'Cache-Control: no-cache' https://raw.githubusercontent.com/fossas/fossa-cli/master/install.sh | sudo bash"

script:
  - ant travis
  - fossa init
  - fossa analyze

after_success:
  - bash <(curl -s https://codecov.io/bash)
